// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: trie.proto

/*
Package triepb is a generated protocol buffer package.

It is generated from these files:
	trie.proto

It has these top-level messages:
	Child
	Node
*/
package triepb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Child struct {
	Type uint32 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Val  []byte `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
}

func (m *Child) Reset()                    { *m = Child{} }
func (m *Child) String() string            { return proto.CompactTextString(m) }
func (*Child) ProtoMessage()               {}
func (*Child) Descriptor() ([]byte, []int) { return fileDescriptorTrie, []int{0} }

func (m *Child) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Child) GetVal() []byte {
	if m != nil {
		return m.Val
	}
	return nil
}

type Node struct {
	Children []*Child `protobuf:"bytes,1,rep,name=children" json:"children,omitempty"`
}

func (m *Node) Reset()                    { *m = Node{} }
func (m *Node) String() string            { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()               {}
func (*Node) Descriptor() ([]byte, []int) { return fileDescriptorTrie, []int{1} }

func (m *Node) GetChildren() []*Child {
	if m != nil {
		return m.Children
	}
	return nil
}

func init() {
	proto.RegisterType((*Child)(nil), "triepb.child")
	proto.RegisterType((*Node)(nil), "triepb.node")
}

func init() { proto.RegisterFile("trie.proto", fileDescriptorTrie) }

var fileDescriptorTrie = []byte{
	// 122 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x29, 0xca, 0x4c,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03, 0xb1, 0x0b, 0x92, 0x94, 0x74, 0xb9, 0x58,
	0x93, 0x33, 0x32, 0x73, 0x52, 0x84, 0x84, 0xb8, 0x58, 0x4a, 0x2a, 0x0b, 0x52, 0x25, 0x18, 0x15,
	0x18, 0x35, 0x78, 0x83, 0xc0, 0x6c, 0x21, 0x01, 0x2e, 0xe6, 0xb2, 0xc4, 0x1c, 0x09, 0x26, 0x05,
	0x46, 0x0d, 0x9e, 0x20, 0x10, 0x53, 0xc9, 0x90, 0x8b, 0x25, 0x2f, 0x3f, 0x25, 0x55, 0x48, 0x93,
	0x8b, 0x03, 0xac, 0xad, 0x28, 0x35, 0x4f, 0x82, 0x51, 0x81, 0x59, 0x83, 0xdb, 0x88, 0x57, 0x0f,
	0x62, 0xa2, 0x1e, 0x58, 0x3c, 0x08, 0x2e, 0x9d, 0xc4, 0x06, 0xb6, 0xd0, 0x18, 0x10, 0x00, 0x00,
	0xff, 0xff, 0xb0, 0x63, 0xe9, 0x0d, 0x7e, 0x00, 0x00, 0x00,
}
